version: '2'
services:
  pingpong:
   build: .

  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    links:
     - pingpong

    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
#    command: [nginx-debug, '-g', 'daemon off;']



